apiVersion: v1
kind: ConfigMap
metadata:
  namespace: gitbook
  name: configmap-nginx
data:
  nginx.conf: |-
    worker_processes auto;
    
    events {
        worker_connections 8000;
        multi_accept on;
    }
    
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
    
        log_format compression '$remote_addr - $remote_user [$time_local] '
            '"$request" $status $upstream_addr '
            '"$http_referer" "$http_user_agent"';
    
        server {
            listen 80;
            underscores_in_headers on;
            access_log /var/log/nginx/access.log compression;
    
            root /var/www;
            
            index index.html index.htm;
    
            location / {
                try_files $uri $uri/ /index.html;
            }
    
            location /healthz {
                if ($http_x_custom_header = "healthz"){ 
                    return 200 "healthz";
                }
                return 403; 
            }
    
            location ~ ^.+\..+$ {
                try_files $uri =404;
            }
        }
    }
